<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tags = [
            // Tech & Web Tags
            ['name' => 'HTML', 'slug' => 'html'],
            ['name' => 'CSS', 'slug' => 'css'],
            ['name' => 'JavaScript', 'slug' => 'javascript'],
            ['name' => 'Python', 'slug' => 'python'],
            ['name' => 'PHP', 'slug' => 'php'],
            ['name' => 'React', 'slug' => 'react'],
            ['name' => 'Livewire', 'slug' => 'livewire'],
            ['name' => 'Laravel', 'slug' => 'laravel'],
            ['name' => 'Vue.js', 'slug' => 'vue-js'],
            ['name' => 'Node.js', 'slug' => 'node-js'],
            ['name' => 'DevOps', 'slug' => 'devops'],
            ['name' => 'Cloud', 'slug' => 'cloud'],
            ['name' => 'API', 'slug' => 'api'],
            ['name' => 'AI', 'slug' => 'ai'],
            ['name' => 'Machine Learning', 'slug' => 'machine-learning'],
            ['name' => 'Blockchain', 'slug' => 'blockchain'],
            ['name' => 'Cybersecurity', 'slug' => 'cybersecurity'],
            ['name' => 'UI/UX', 'slug' => 'ui-ux'],
            ['name' => 'Web Design', 'slug' => 'web-design'],
            ['name' => 'IoT', 'slug' => 'iot'],
            ['name' => 'Docker', 'slug' => 'docker'],
            ['name' => 'AWS', 'slug' => 'aws'],
            ['name' => 'MySQL', 'slug' => 'mysql'],
            ['name' => 'PostgreSQL', 'slug' => 'postgresql'],
            ['name' => 'MongoDB', 'slug' => 'mongodb'],
            ['name' => 'REST', 'slug' => 'rest'],
            ['name' => 'GraphQL', 'slug' => 'graphql'],
            ['name' => 'Tutorial', 'slug' => 'tutorial'],
            ['name' => 'Best Practices', 'slug' => 'best-practices'],
            ['name' => 'Security', 'slug' => 'security'],
            ['name' => 'Performance', 'slug' => 'performance'],
            ['name' => 'Testing', 'slug' => 'testing'],
            // Additional Tech SEO Tags
            ['name' => 'Web Development', 'slug' => 'web-development'],
            ['name' => 'Frontend Development', 'slug' => 'frontend-development'],
            ['name' => 'Backend Development', 'slug' => 'backend-development'],
            ['name' => 'Full Stack Development', 'slug' => 'full-stack-development'],
            ['name' => 'Mobile Development', 'slug' => 'mobile-development'],
            ['name' => 'Progressive Web Apps', 'slug' => 'progressive-web-apps'],
            ['name' => 'Responsive Design', 'slug' => 'responsive-design'],
            ['name' => 'Web Accessibility', 'slug' => 'web-accessibility'],
            ['name' => 'WCAG Compliance', 'slug' => 'wcag-compliance'],
            ['name' => 'User Experience', 'slug' => 'user-experience'],
            ['name' => 'User Interface Design', 'slug' => 'user-interface-design'],
            ['name' => 'Interaction Design', 'slug' => 'interaction-design'],
            ['name' => 'Web Performance', 'slug' => 'web-performance'],
            ['name' => 'Core Web Vitals', 'slug' => 'core-web-vitals'],
            ['name' => 'Page Speed', 'slug' => 'page-speed'],
            ['name' => 'Technical SEO', 'slug' => 'technical-seo'],
            ['name' => 'On-Page SEO', 'slug' => 'on-page-seo'],
            ['name' => 'Off-Page SEO', 'slug' => 'off-page-seo'],
            ['name' => 'Local SEO', 'slug' => 'local-seo'],
            ['name' => 'E-commerce SEO', 'slug' => 'e-commerce-seo'],

            // AI & ML Enhanced Tags
            ['name' => 'Artificial Intelligence', 'slug' => 'artificial-intelligence'],
            ['name' => 'Generative AI', 'slug' => 'generative-ai'],
            ['name' => 'Machine Learning Algorithms', 'slug' => 'machine-learning-algorithms'],
            ['name' => 'Deep Learning', 'slug' => 'deep-learning'],
            ['name' => 'Natural Language Processing', 'slug' => 'natural-language-processing'],
            ['name' => 'Computer Vision', 'slug' => 'computer-vision'],
            ['name' => 'AI Tools', 'slug' => 'ai-tools'],
            ['name' => 'AI Ethics', 'slug' => 'ai-ethics'],
            ['name' => 'AI Automation', 'slug' => 'ai-automation'],
            ['name' => 'Predictive Analytics', 'slug' => 'predictive-analytics'],
            ['name' => 'Big Data', 'slug' => 'big-data'],
            ['name' => 'Data Science', 'slug' => 'data-science'],
            ['name' => 'Neural Networks', 'slug' => 'neural-networks'],
            ['name' => 'ChatGPT', 'slug' => 'chatgpt'],
            ['name' => 'Claude AI', 'slug' => 'claude-ai'],
            ['name' => 'GPT-4', 'slug' => 'gpt-4'],

            // Cloud & DevOps Enhanced
            ['name' => 'Cloud Computing', 'slug' => 'cloud-computing'],
            ['name' => 'Cloud Migration', 'slug' => 'cloud-migration'],
            ['name' => 'Serverless', 'slug' => 'serverless'],
            ['name' => 'Microservices', 'slug' => 'microservices'],
            ['name' => 'Kubernetes', 'slug' => 'kubernetes'],
            ['name' => 'CI/CD', 'slug' => 'ci-cd'],
            ['name' => 'Infrastructure as Code', 'slug' => 'infrastructure-as-code'],
            ['name' => 'Azure', 'slug' => 'azure'],
            ['name' => 'Google Cloud', 'slug' => 'google-cloud'],
            ['name' => 'DigitalOcean', 'slug' => 'digitalocean'],
            ['name' => 'VPS Hosting', 'slug' => 'vps-hosting'],
            ['name' => 'Cloud Security', 'slug' => 'cloud-security'],
            ['name' => 'Data Privacy', 'slug' => 'data-privacy'],
            ['name' => 'GDPR Compliance', 'slug' => 'gdpr-compliance'],
            ['name' => 'CCPA Compliance', 'slug' => 'ccpa-compliance'],

            // Business & Industry Tags
            ['name' => 'Entrepreneurship', 'slug' => 'entrepreneurship'],
            ['name' => 'Startup', 'slug' => 'startup'],
            ['name' => 'Business Strategy', 'slug' => 'business-strategy'],
            ['name' => 'Digital Marketing', 'slug' => 'digital-marketing'],
            ['name' => 'SEO', 'slug' => 'seo'],
            ['name' => 'Content Marketing', 'slug' => 'content-marketing'],
            ['name' => 'Social Media', 'slug' => 'social-media'],
            ['name' => 'Fintech', 'slug' => 'fintech'],
            ['name' => 'E-commerce', 'slug' => 'e-commerce'],
            ['name' => 'Productivity', 'slug' => 'productivity'],
            ['name' => 'Leadership', 'slug' => 'leadership'],
            ['name' => 'Innovation', 'slug' => 'innovation'],
            ['name' => 'Data Analytics', 'slug' => 'data-analytics'],
            ['name' => 'Remote Work', 'slug' => 'remote-work'],
            ['name' => 'SaaS', 'slug' => 'saas'],
            // Enhanced Business Tags
            ['name' => 'Business Growth', 'slug' => 'business-growth'],
            ['name' => 'Startup Funding', 'slug' => 'startup-funding'],
            ['name' => 'Business Development', 'slug' => 'business-development'],
            ['name' => 'Digital Transformation', 'slug' => 'digital-transformation'],
            ['name' => 'Business Intelligence', 'slug' => 'business-intelligence'],
            ['name' => 'Customer Experience', 'slug' => 'customer-experience'],
            ['name' => 'Customer Relationship Management', 'slug' => 'customer-relationship-management'],
            ['name' => 'Marketing Automation', 'slug' => 'marketing-automation'],
            ['name' => 'Conversion Rate Optimization', 'slug' => 'conversion-rate-optimization'],
            ['name' => 'Email Marketing', 'slug' => 'email-marketing'],
            ['name' => 'PPC Advertising', 'slug' => 'ppc-advertising'],
            ['name' => 'Google Ads', 'slug' => 'google-ads'],
            ['name' => 'Facebook Ads', 'slug' => 'facebook-ads'],
            ['name' => 'Influencer Marketing', 'slug' => 'influencer-marketing'],
            ['name' => 'Brand Strategy', 'slug' => 'brand-strategy'],
            ['name' => 'Market Research', 'slug' => 'market-research'],
            ['name' => 'Competitive Analysis', 'slug' => 'competitive-analysis'],
            ['name' => 'Business Model', 'slug' => 'business-model'],
            ['name' => 'Revenue Model', 'slug' => 'revenue-model'],
            ['name' => 'Pricing Strategy', 'slug' => 'pricing-strategy'],
            ['name' => 'Sales Funnel', 'slug' => 'sales-funnel'],
            ['name' => 'Lead Generation', 'slug' => 'lead-generation'],
            ['name' => 'Customer Acquisition', 'slug' => 'customer-acquisition'],
            ['name' => 'Customer Retention', 'slug' => 'customer-retention'],
            ['name' => 'Churn Reduction', 'slug' => 'churn-reduction'],
            ['name' => 'Business Scaling', 'slug' => 'business-scaling'],
            ['name' => 'Operations Management', 'slug' => 'operations-management'],
            ['name' => 'Project Management', 'slug' => 'project-management'],
            ['name' => 'Agile Methodology', 'slug' => 'agile-methodology'],
            ['name' => 'Scrum', 'slug' => 'scrum'],
            ['name' => 'Kanban', 'slug' => 'kanban'],
            ['name' => 'Lean Startup', 'slug' => 'lean-startup'],
            ['name' => 'Growth Hacking', 'slug' => 'growth-hacking'],
            ['name' => 'Viral Marketing', 'slug' => 'viral-marketing'],

            // Cybersecurity Enhanced
            ['name' => 'Data Security', 'slug' => 'data-security'],
            ['name' => 'Network Security', 'slug' => 'network-security'],
            ['name' => 'Information Security', 'slug' => 'information-security'],
            ['name' => 'Cyber Threats', 'slug' => 'cyber-threats'],
            ['name' => 'Ransomware', 'slug' => 'ransomware'],
            ['name' => 'Phishing', 'slug' => 'phishing'],
            ['name' => 'Malware', 'slug' => 'malware'],
            ['name' => 'Data Breach', 'slug' => 'data-breach'],
            ['name' => 'Incident Response', 'slug' => 'incident-response'],
            ['name' => 'Security Audit', 'slug' => 'security-audit'],
            ['name' => 'Penetration Testing', 'slug' => 'penetration-testing'],
            ['name' => 'Vulnerability Assessment', 'slug' => 'vulnerability-assessment'],
            ['name' => 'Zero Trust Security', 'slug' => 'zero-trust-security'],
            ['name' => 'Multi-Factor Authentication', 'slug' => 'multi-factor-authentication'],
            ['name' => 'Encryption', 'slug' => 'encryption'],
            ['name' => 'Blockchain Security', 'slug' => 'blockchain-security'],
            ['name' => 'IoT Security', 'slug' => 'iot-security'],
            ['name' => 'Compliance', 'slug' => 'compliance'],
            ['name' => 'Risk Management', 'slug' => 'risk-management'],
            ['name' => 'Business Continuity', 'slug' => 'business-continuity'],
            ['name' => 'Disaster Recovery', 'slug' => 'disaster-recovery'],

            // Productivity & Future of Work
            ['name' => 'Work-Life Balance', 'slug' => 'work-life-balance'],
            ['name' => 'Time Management', 'slug' => 'time-management'],
            ['name' => 'Workflow Automation', 'slug' => 'workflow-automation'],
            ['name' => 'Collaboration Tools', 'slug' => 'collaboration-tools'],
            ['name' => 'Virtual Teams', 'slug' => 'virtual-teams'],
            ['name' => 'Asynchronous Communication', 'slug' => 'asynchronous-communication'],
            ['name' => 'Knowledge Management', 'slug' => 'knowledge-management'],
            ['name' => 'Digital Workplace', 'slug' => 'digital-workplace'],
            ['name' => 'Employee Engagement', 'slug' => 'employee-engagement'],
            ['name' => 'Talent Management', 'slug' => 'talent-management'],
            ['name' => 'Professional Development', 'slug' => 'professional-development'],
            ['name' => 'Career Growth', 'slug' => 'career-growth'],
            ['name' => 'Work Culture', 'slug' => 'work-culture'],
            ['name' => 'Diversity and Inclusion', 'slug' => 'diversity-and-inclusion'],
            ['name' => 'Mental Health', 'slug' => 'mental-health'],
            ['name' => 'Burnout Prevention', 'slug' => 'burnout-prevention'],
            ['name' => 'Gig Economy', 'slug' => 'gig-economy'],
            ['name' => 'Freelancing', 'slug' => 'freelancing'],
            ['name' => 'Side Hustle', 'slug' => 'side-hustle'],

            // Additional Impactful Tags
            ['name' => 'Future of Work', 'slug' => 'future-of-work'],
            ['name' => 'Ethical Technology', 'slug' => 'ethical-technology'],
            ['name' => 'Employee Experience', 'slug' => 'employee-experience'],
            ['name' => 'AI for Marketing', 'slug' => 'ai-for-marketing'],
            ['name' => 'Conversational UI', 'slug' => 'conversational-ui'],
            ['name' => 'Accessibility', 'slug' => 'accessibility'],
            ['name' => 'Micro-interactions', 'slug' => 'micro-interactions'],
            ['name' => 'User Research', 'slug' => 'user-research'],
            ['name' => 'Design Thinking', 'slug' => 'design-thinking'],
            ['name' => 'Agile Development', 'slug' => 'agile-development'],
            ['name' => 'Sustainable Technology', 'slug' => 'sustainable-technology'],
            ['name' => 'Green Computing', 'slug' => 'green-computing'],
            ['name' => 'Tech Ethics', 'slug' => 'tech-ethics'],
            ['name' => 'Digital Rights', 'slug' => 'digital-rights'],
            ['name' => 'Open Source', 'slug' => 'open-source'],
            ['name' => 'API Economy', 'slug' => 'api-economy'],
            ['name' => 'Platform Business', 'slug' => 'platform-business'],
            ['name' => 'Subscription Model', 'slug' => 'subscription-model'],
            ['name' => 'Freemium', 'slug' => 'freemium'],
            ['name' => 'Monetization Strategies', 'slug' => 'monetization-strategies']
        ];

        foreach ($tags as $tag) {
            \App\Models\Tag::create($tag);
        }
    }
}
